version: '3'

services:
  web:
    build: .
    command:  bash -c "python manage.py migrate && python manage.py loaddata fixtures/*.json && python cron_script.py && python manage.py runserver 0.0.0.0:8000"
#    command:  bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    environment:
      POSTGRES_PASSWORD: jfFEd84HWFj
      EB_BEARER: SAFEXY2AQJ4Y2DAHFG3A
      DJANGO_LOG_LEVEL: INFO
      DEBUG: 'True'
    ports:
      - "8001:8000"
    depends_on:
      - postgres

  postgres:
    environment:
      POSTGRES_PASSWORD: jfFEd84HWFj
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 1m

volumes:
  pg_data: