# Generated by Django 2.1 on 2019-03-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190328_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='updated',
            new_name='changed',
        ),
    ]
